source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }gem "sprockets-rails"
gem 'pg'
gem "puma", "~> 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "redis", "~> 4.0"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem "bootsnap", require: false
gem 'bootstrap'
gem "sassc-rails"
gem 'devise'
gem 'autoprefixer-rails', '10.2.5'
gem 'simple_form'
gem "pundit"

group :development, :test do
  gem 'factory_bot_rails'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'dotenv-rails'
  gem "rubocop-performance"
  gem 'rubocop-rails'
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  gem "web-console"
  gem "letter_opener_web", "~> 1.0"
end

group :test do
  gem 'rspec-rails'
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end